---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvol-demo
  labels:
    name: my-sql
spec:
  containers:
    - name: mysql-contianer
      image: mysql:8-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: suresh
        - name: MYSQL_PASSWORD
          value: suresh1234
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: mysql-aws-claim
        readOnly: false    