apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    
    name: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
      volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-vol-
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: mysql-aws-claim
        readOnly: false  