---
apiversion: v1
kind: Service
metadata:
  name: svc-gameoflife
spec:
  type: ClusterIP
  selector:
    app: gameoflife
  ports:
    name: internal
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameoflife
  annotations:
    kubernetes.io/ingress.class: "alb"
spec:
  rules:
  - http:
      paths:
      - path: /gameoflife*
        backend:
          service:
            name: external
            port:
              number: 8080
        pathType: Exact